FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir psycopg2-binary cassandra-driver kafka-python

COPY ./apps/actuator.py .
COPY ./apps/health_check.py .

ENV PYTHONUNBUFFERED=1

CMD ["python3", "actuator.py"]