services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # EXTERNAL for connecting from outside docker container.
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093, EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'Mq699i8pS9u8z_v1XgA8pA'
    volumes:
      - kafka_data:/tmp/kafka-logs
    user: root

  kafka-init:
    image: apache/kafka:4.1.1
    container_name: kafka-init
    depends_on:
      - kafka
    init: true
    command: /bin/bash -c "/opt/kafka/bin/kafka-topics.sh --create --topic query-logs --if-not-exists --replication-factor 1 --partitions 1 --bootstrap-server kafka:9092"

  cassandra:
    image: cassandra:5.0.6
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  
  cassandra-init:
    image: cassandra:5.0.6
    container_name: cassandra-init
    depends_on:
      - cassandra
    volumes:
      - ./apps:/apps
    command: >
      /bin/bash -c "
      echo 'Waiting for Cassandra to be reachable...' &&
      until cqlsh cassandra 9042 -e 'describe cluster' > /dev/null 2>&1; do
        sleep 5
      done;
      echo 'Applying schema...' &&
      cqlsh cassandra 9042 -f /apps/schema.cql &&
      echo 'Schema applied successfully!'"
  
  postgres:
    image: postgres:15.15-trixie
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres 
      -c log_statement=all 
      -c logging_collector=on 
      -c log_directory=/var/log/postgresql 
      -c log_filename=postgresql.log
    volumes:
      - pg_logs:/var/log/postgresql
      - postgres_data:/var/lib/postgresql/data
  
  watcher:
    image: python:3.13-slim
    container_name: watcher
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./apps:/apps
      - pg_logs:/var/log/postgresql:ro # Read-only
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install kafka-python && python3 /apps/watcher.py"

  spark-master:
    image: apache/spark:4.1.0-scala2.13-java21-python3-r-ubuntu
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080" # Web UI
      - "7077:7077" # Spark Master port
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077 --webui-port 8080

  spark-worker:
    image: apache/spark:4.1.0-scala2.13-java21-python3-r-ubuntu
    user: root
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-submit:
    image: apache/spark:4.1.0-scala2.13-java21-python3-r-ubuntu
    container_name: spark-submit
    user: root
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./apps:/opt/spark-apps
    environment:
      # need this because default directory is not writable in official apache image.
      - SPARK_SUBMIT_OPTS=-Divy.cache.dir=/tmp/.ivy -Divy.home=/tmp/.ivy
    command: >
      /bin/bash -c "
      echo 'Waiting for Kafka and Cassandra...' &&
      until (echo > /dev/tcp/kafka/9092) 2>/dev/null; do sleep 1; done;
      until (echo > /dev/tcp/cassandra/9042) 2>/dev/null; do sleep 2; done;
      
      echo 'Starting Spark Job...' &&
      /opt/spark/bin/spark-submit 
      --master spark://spark-master:7077
      --packages org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.0,com.datastax.spark:spark-cassandra-connector_2.13:3.5.0
      /opt/spark-apps/spark_processor.py"

  actuator:
    image: python:3.13-slim
    container_name: actuator
    depends_on:
      - cassandra
      - postgres
    volumes:
      - ./apps:/apps
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install psycopg2-binary cassandra-driver && python3 /apps/actuator.py"


volumes:
  kafka_data:
  cassandra_data:
  postgres_data:
  pg_logs:
