# TODO: create environment vars with all defaults

services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # EXTERNAL for connecting from outside docker container.
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093, EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'Mq699i8pS9u8z_v1XgA8pA'
    volumes:
      - kafka_data:/tmp/kafka-logs
    user: root


  cassandra:
    image: cassandra:5.0.6
    container_name: cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra

  
  postgres:
    image: postgres:15.15-trixie
    container_name: postgres
    command: >
      postgres 
      -c log_statement=all 
      -c logging_collector=on 
      -c log_directory=/var/log/postgresql 
      -c log_filename=postgresql.log
    volumes:
      - pg_logs:/var/log/postgresql # Shared with Watcher
      - postgres_data:/var/lib/postgresql/data # Persistent User Dat
  
  watcher:
    image: auto-idx-watcher:1.0
    container_name: watcher
    volumes:
      - pg_logs:/var/log/postgresql:ro # Only needs the logs
    environment:
      - KAFKA_BROKERS=kafka:9092

  spark:
    image: my-spark-processor:1.0
    container_name: spark
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CASSANDRA_HOSTS=cassandra
    volumes:
      - spark_checkpoints:/opt/spark-apps/checkpoints

  actuator:
    image: my-actuator:1.0
    container_name: actuator
    environment:
      - DB_HOST=postgres
      - DB_NAME=testdb
      - DB_USER=admin
      - DB_PASS=password
      - CASSANDRA_HOSTS=cassandra


volumes:
  kafka_data:
  cassandra_data:
  postgres_data:
  pg_logs:
  spark_checkpoints:
