FROM apache/spark:3.5.0-python3

USER root
WORKDIR /opt/spark-apps

RUN pip install --no-cache-dir cassandra-driver kafka-python

RUN mkdir -p /opt/spark-apps/checkpoints && chmod -R 777 /opt/spark-apps/checkpoints

COPY ./apps/spark_processor.py .
COPY ./apps/health_check.py .

CMD /bin/bash -c "echo 'Starting Spark Job...' && \
      /opt/spark/bin/spark-submit \
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0 \
      /opt/spark-apps/spark_processor.py"